package tools

import (
	"context"
	"encoding/json"
	"fmt"
	miniagent "github.com/justphantom/miniagent/internal/miniagent"
	"os"
	"os/exec"
	"strings"
	"time"
)

type lintArgs struct {
	Subcommand string `json:"subcommand"`
	Args       string `json:"args,omitempty"`
}

// run/version/linters 是 verify-gate 末步的最小集：跑 lint、查版本、查可用 linter 列表。
// cache clean/types/internal/autogenerated 等辅助子命令排除（收紧原则）。
// --fix 会自动改写源码，等同写工具且绕过 confineWrap，必须拒绝。
var allowedLintSubcommands = map[string]bool{
	"run": true, "version": true, "linters": true,
}
var deniedLintArgPrefixes = []string{"--fix", "-fix", "--write", "-w", "--enable-all", "--new", "--new-from-rev"}

func LintTool(workspaceRoot string, timeout time.Duration) miniagent.Tool {
	if timeout <= 0 {
		timeout = shellTimeout
	}
	return miniagent.Tool{
		Name:        "golangci-lint",
		Description: "Constrained golangci-lint for Go static analysis: run/version/linters. run executes enabled linters on the workspace (verify-gate last step). --fix/--write/--enable-all/--new* are blocked (auto-rewrites source or floods).",
		Parameters: object(map[string]any{
			"subcommand": map[string]any{"type": "string", "description": "golangci-lint subcommand"},
			"args":       map[string]any{"type": "string", "description": `Additional arguments as ONE string; shell-style quoting keeps spaces intact. --fix/--write/--enable-all/--new* are rejected`},
		}, "subcommand"),
		ResultLimit: miniagent.MaxToolResultInHistory,
		// lint 结果按文件逐条输出，截断时保 head+tail 才能同时看到首个与末个问题文件。
		SplitTruncate: true,
		Call: func(ctx context.Context, args string) miniagent.ToolResult {
			return runWithTimeout(ctx, timeout, "golangci-lint", func(rctx context.Context) miniagent.ToolResult {
				return runLint(rctx, workspaceRoot, args)
			})
		},
	}
}

func runLint(ctx context.Context, workspaceRoot, args string) miniagent.ToolResult {
	var a lintArgs
	if err := json.Unmarshal([]byte(args), &a); err != nil {
		return miniagent.ToolResult{IsError: true, Output: fmt.Sprintf("argument parsing failed (args must be a JSON object with string fields, e.g. {\"subcommand\":\"run\",\"args\":\"./...\"}): %v", err)}
	}
	if strings.TrimSpace(a.Subcommand) == "" {
		return miniagent.ToolResult{IsError: true, Output: "missing argument: subcommand"}
	}
	if !allowedLintSubcommands[a.Subcommand] {
		return miniagent.ToolResult{IsError: true, Output: fmt.Sprintf("golangci-lint %q is not allowed in default mode; use one of: run, version, linters", a.Subcommand)}
	}
	fields := splitArgs(a.Args)
	for _, f := range fields {
		for _, p := range deniedLintArgPrefixes {
			if strings.HasPrefix(f, p) {
				return miniagent.ToolResult{IsError: true, Output: fmt.Sprintf("golangci-lint %s option %q rewrites source or floods linters; blocked", a.Subcommand, f)}
			}
		}
	}
	cmdArgs := append([]string{a.Subcommand}, fields...)
	bin, argv := rtkWrap("golangci-lint", []string{"golangci-lint"}, cmdArgs)
	cmd := exec.CommandContext(ctx, bin, argv...)
	cmd.Dir = resolveModuleRoot(workspaceRoot)
	cmd.Env = scrubEnv(os.Environ())
	setPGID(cmd)
	body, err := runLimitedOutput(ctx, cmd)
	if err != nil {
		return miniagent.ToolResult{IsError: true, Output: fmt.Sprintf("golangci-lint %s failed: %v\n%s", a.Subcommand, err, body)}
	}
	if body == "" {
		body = "(no output)\n"
	}
	return miniagent.ToolResult{Output: body}
}
