package tools

import (
	"context"
	miniagent "github.com/justphantom/miniagent/internal/miniagent"
	"os"
	"os/exec"
	"strings"
	"time"
)

type lintArgs struct {
	Subcommand string `json:"subcommand"`
	Args       string `json:"args,omitempty"`
}

// run/version/linters 是 verify-gate 末步的最小集：跑 lint、查版本、查可用 linter 列表。
// cache clean/types/internal/autogenerated 等辅助子命令排除（收紧原则）。
// --fix 会自动改写源码，等同写工具且绕过 confineWrap，必须拒绝。
var allowedLintSubcommands = map[string]bool{
	"run": true, "version": true, "linters": true,
}

// lintDeniedOptions：改写源码（--fix/-f 与 --fix 粘合）或洪水级启用（--enable-all/--new* 全族，
// 含 -n 短形与 --new-from-patch/--new-from-merge-base）；--output.*.path 把报告写到任意路径
// （与 git deny 表的 output 同类）。旧前缀 "-w" 误杀 golangci-lint run -w 之类无关注法且
// golangci-lint 无 -w 改写语义，删除。
var lintDeniedOptions = []optSpec{
	// -f 是 golangci-lint 的 --fix 短形（无粘合值），全等匹配不误杀 -fix 类外推。
	{shorts: []string{"-f", "-n"}, longs: []string{"fix", "write", "enable-all", "new", "new-from-rev", "new-from-patch", "new-from-merge-base"}, reason: reasonWrite},
	// 名字带 '.' 的长选项：matchOption 只在 '=' 处截断，点号参与全等比较，无需前缀推断。
	{longs: []string{"output.json.path"}, reason: reasonWrite},
}

func LintTool(workspaceRoot string, timeout time.Duration, maxOutputChars int) miniagent.Tool {
	if timeout <= 0 {
		timeout = shellTimeout
	}
	if maxOutputChars <= 0 {
		maxOutputChars = maxShellOutputChars
	}
	return miniagent.Tool{
		Name:        "golangci-lint",
		Description: "Constrained golangci-lint for Go static analysis: " + sortedNames(allowedLintSubcommands) + ". run executes enabled linters on the workspace (verify-gate last step). --fix/--write/--enable-all/--new* (incl. -n, --new-from-patch, --new-from-merge-base) and --output.json.path (report writes) are blocked. Timeout " + timeout.String() + "; lint findings exit non-zero — that is a normal result, not a tool failure.",
		Parameters: object(map[string]any{
			"subcommand": map[string]any{"type": "string", "description": "golangci-lint subcommand"},
			"args":       map[string]any{"type": "string", "description": `Additional arguments as ONE string; shell-style quoting keeps spaces intact. --fix/--write/--enable-all/--new* (incl. -n)/--output.json.path are rejected`},
		}, "subcommand"),
		ResultLimit: miniagent.MaxToolResultInHistory,
		// lint 结果按文件逐条输出，截断时保 head+tail 才能同时看到首个与末个问题文件。
		SplitTruncate: true,
		Call: func(ctx context.Context, args string) miniagent.ToolResult {
			return runWithTimeout(ctx, timeout, "golangci-lint", func(rctx context.Context) miniagent.ToolResult {
				return runLint(rctx, workspaceRoot, args, maxOutputChars)
			})
		},
	}
}

func runLint(ctx context.Context, workspaceRoot, args string, maxOutputChars int) miniagent.ToolResult {
	var a lintArgs
	if err := decodeStrict(args, &a); err != nil {
		return denyResult("argument parsing failed (args must be a JSON object with string fields subcommand/args, e.g. {\"subcommand\":\"run\",\"args\":\"./...\"}): %v", err)
	}
	sub := strings.TrimSpace(a.Subcommand)
	if sub == "" {
		return denyResult("missing argument: subcommand")
	}
	if !allowedLintSubcommands[sub] {
		return denyResult("golangci-lint %q is not allowed in default mode; use one of: %s", sub, sortedNames(allowedLintSubcommands))
	}
	fields, qerr := splitArgsStrict(a.Args)
	if qerr != "" {
		return denyResult("args %s", qerr)
	}
	if op := checkShellMetachars(a.Args); op != "" {
		return denyResult("%s", denyShellMetachars(a.Args))
	}
	fields = stripDupSubcommand(sub, fields)
	if tok, spec, hit := checkDeniedOptions(fields, lintDeniedOptions); hit {
		return denyResult("golangci-lint %s option %q (%s) %s; blocked", sub, tok, spec.joinNames(), spec.reason)
	}
	cmdArgs := append([]string{sub}, fields...)
	// 不经 rtk 代理：rtk 的 golangci-lint 包装层在有 findings 时也退出 0（实测 6/6），
	// 抹掉 exit_code 契约（22fac84 为 lint 打开 exit_code 正是为此）。
	cmd := exec.CommandContext(ctx, "golangci-lint", cmdArgs...)
	cmd.Dir = resolveModuleRoot(workspaceRoot)
	cmd.Env = scrubEnv(os.Environ())
	setPGID(cmd)
	body, err := runLimitedOutput(ctx, cmd, maxOutputChars)
	if err != nil {
		return exitAwareResult("golangci-lint", sub, body, err)
	}
	if body == "" {
		body = "(no output)\n"
	}
	return miniagent.ToolResult{Output: body}
}
